### ISSUE TITLE
Invalid template for menu

### ISSUE THREAD

**Issue by evandandrea** [alexanderwe/checksum-validator#23] opened 2018-08-13 13:45 UTC
* **I'm submitting a ...**
  * [x] bug report
  * [ ] feature request

- **What is the current behavior?**

I get an "invalid template for menu" error when it first starts up. This is running the `.snap`, but the error looks unrelated.

* **Please tell me about your environment:**

- version: 1.1.4
- OS: Ubuntu

**Comment by alexanderwe** [comment] 2018-08-18 19:41
Thanks for submitting the issue, the cause for this issue was that I forgot that my MenuBuilder did not address Linux builds correctly. 

This was fixed with commit https://github.com/alexanderwe/checksum-validator/commit/e7289ec2f98a3041592e1b2376f6a77d1350dbd8.

New release: https://github.com/alexanderwe/checksum-validator/releases/tag/v1.1.5

**Closed** 2018-08-18 20:05 UTC
Labels: bug
